### Get all players

GET http://localhost:8080/api/players

### Get single player

GET http://localhost:8080/api/player/c4804e0f-769e-4ab9-9ebe-0578fb4f00a4

### Get single player, not existing

GET http://localhost:8080/api/characters/c4804e0f-769e-4ab9-9ebe-0578fb4f00aa

### Create new player

PUT http://localhost:8080/api/players/c4804e0f-769e-4ab9-9ebe-0578fb4f00a9

{
    "name": "Joao",
    "surname": "Felix",
    "age": 24,
    "club": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a1"
}

http://localhost:8080/api/clubs/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1/players

### Delete player.

DELETE http://localhost:8080/api/players/c4804e0f-769e-4ab9-9ebe-0578fb4f00a9

### Get all clubs

GET http://localhost:8080/api/clubs

### Get single club

GET http://localhost:8080/api/clubs/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1

### Get single club, not existing

GET http://localhost:8080/api/clubs/c4804e0f-769e-4ab9-9ebe-0578fb4f10a1

### Add new club

PUT http://localhost:8080/api/clubs/c4804e0f-769e-4ab9-9ebe-0578fb4f10a9

{
    "name": "Juventus",
    "foundingYear": 189
}

### Delete club

DELETE http://localhost:8080/api/clubs/c4804e0f-769e-4ab9-9ebe-0578fb4f10a9

### Get club players

GET http://localhost:8080/api/clubs/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1/players

